---
- hosts: localhost
  connection: local
  vars:
    bucket: "www.ylitalot.net"
  tasks:
  - name: create storage
    command: "gsutil -q mb -c regional -l us-central1 -p ylitalotcom gs://{{bucket}}"
    ignore_errors: yes
  - name: sync content
    command: "gsutil rsync -r {{item.src}}/ gs://{{bucket}}/{{item.dest}}"
    args:
      chdir: ylitalot.net/_site
    with_items:
    - {src: "images", dest: "images"}
    - {src: ".", dest: ""}
  - name: make it all public
    command: "gsutil defacl ch -u AllUsers:R gs://{{bucket}}"
  - name: make it website
    command: "gsutil web set -m index.html -e 404.html gs://{{bucket}}"
