---
- hosts: localhost
  vars:
    site: ylitalot.net
  tasks:
  ###
  # setup
  ###
  - name: install bundler
    gem: name={{item}} state=present
    with_items:
      - bundler
  - name: install gems
    shell: bundle install
    args:
      chdir: "files/override-{{site}}"
  - name: git update
    git: repo={{item.repo}} dest=files/{{item.dest}} update=yes
    with_items:
      - { repo: "git@github.com:jackmoore/colorbox.git", dest: "colorbox.git" }
      - { repo: "git@bitbucket.org:jylitalo/{{site}}.git", dest: "{{site}}-content.git" }
  ###
  # .gitignore
  ###
  - name: .gitignore exists
    file: path=.gitignore state=touch
  - name: "add items to .gitignore"
    lineinfile: name=.gitignore regexp="^{{item}}$" line="{{item}}"
    with_items:
      - .gitignore
      - setup.retry
      - files/_images
      - "files/{{site}}"
      - "files/{{site}}-content.git"
      - files/colorbox.git
  ###
  # setup {{site}} with jekyll
  ###
  - name: "{{site}} exists?"
    stat: path=files/{{site}}
    register: jekyll_done
  - name: create site
    shell: "jekyll new {{site}}"
    args:
      chdir: "files"
    when: jekyll_done.stat.exists == False
  - name: clean extra files from jenkins new
    file: path="{{item}}" state=absent
    with_fileglob:
      - "files/{{site}}/about.md"
      - "files/{{site}}/_posts/*-welcome-to-jekyll.markdown"
  ###
  # Colorbox
  ###
  - name: colorbox directories
    file: path="files/{{site}}/{{item}}" state=directory
    with_items:
      - img
      - js/i18n
  - name: copy images from colorbox
    copy: src="{{item}}" dest="files/{{site}}/img/"
    with_fileglob:
      - "files/colorbox.git/example4/images/*"
  - name: copy i18n from colorbox
    copy: src="files/colorbox.git/{{item.src}}" dest="files/{{site}}/{{item.dest}}"
    with_items:
      - { src: "i18n/jquery.colorbox-fi.js", dest: "js/i18n/" }
  - name: copy javascript from colorbox
    copy: src="{{item}}" dest="files/{{site}}/js/"
    with_fileglob:
      - "files/colorbox.git/*.js"
  - name: download jquery
    get_url:
      url: https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js
      dest: "files/{{site}}/js/jquery.min.js"
  ###
  # {{site}} specific stuff
  ###
  - name: "override with {{site}} (copy)"
    copy: src="{{item}}" dest="files/{{site}}/" directory_mode=yes
    with_fileglob:
      - "files/override-{{site}}/*"
  - name: "override with {{site}} (sync)"
    synchronize: src="files/override-{{site}}/{{item}}" dest="files/{{site}}/" archive=yes
    with_items:
      - _layouts
      - _plugins
      - _sass
      - assets
  - name: "sync content to {{site}}"
    synchronize: src="files/{{site}}-content.git/{{item}}" dest="files/{{site}}/" archive=yes
    with_items:
      - _plugins
      - _posts
  - name: finalize setup
    shell: "{{item}}"
    args:
      chdir: "files/{{site}}/"
    with_items:
      - bundle install
      - python ../assets_on_jekyll.py
      - jekyll build
