---
- hosts: localhost
  vars:
    site: ylitalot.net
  tasks:
  - name: install gems
    gem: name={{item}} state=present
    with_items:
      - bundler
      - jekyll
  - name: git update
    git: repo={{item.repo}} dest={{item.dest}} update=yes
    with_items:
      - { repo: "git@github.com:jackmoore/colorbox.git", dest: "colorbox.git" }
  - name: .gitignore exists
    file: path=.gitignore state=touch
  - name: "add items to .gitignore"
    lineinfile: name=.gitignore regexp="^{{item}}$" line="{{item}}"
    with_items:
      - .gitignore
      - setup.retry
      - "{{site}}"
      - colorbox.git
  - name: "{{site}} exists?"
    stat: path={{site}}
    register: jekyll_done
  - name: create site
    shell: "jekyll new {{site}}"
    when: jekyll_done.stat.exists == False
  # Colorbox
  - name: colorbox directories
    file: path="{{site}}/{{item}}" state=directory
    with_items:
      - img
      - js/i18n
  - name: copy images from colorbox
    copy: src="{{item}}" dest="ylitalot.net/img/"
    with_fileglob:
      - "colorbox.git/example4/images/*"
  - name: copy i18n from colorbox
    copy: src="colorbox.git/{{item.src}}" dest="ylitalot.net/{{item.dest}}"
    with_items:
      - { src: "i18n/jquery.colorbox-fi.js", dest: "js/i18n/" }
  - name: copy javascript from colorbox
    copy: src="{{item}}" dest="ylitalot.net/js/"
    with_fileglob:
      - "colorbox.git/*.js"
  # {{site}} specific stuff
  - name: "override with {{site}}"
    copy: src="{{item}}" dest="{{site}}/" directory_mode=yes
    with_fileglob:
      - "files/override-{{site}}/*"
  - name: finalize setup
    shell: "{{item}}"
    args:
      chdir: "{{site}}/"
    with_items:
      - bundle install
      - jekyll serve
